# .github/workflows/devsecops.yml 
name: DevGuard DevSecOps

on:
    push:

permissions:
    contents: read
    packages: write

jobs:
    call-devsecops:
        uses: l3montree-dev/devguard-action/.github/workflows/full.yml@main
        with:
            asset-name: "testorg-1/projects/testgroup/assets/testrepogithub"
            api-url: "https://api.main.devguard.org"
            web-ui: "https://main.devguard.org"
        secrets:
            devguard-token: "${{ secrets.DEVGUARD_TOKEN }}" # you need to create this secret in your GitHub repository settings

    dependency-risk-identification:
        uses: l3montree-dev/devguard-action/.github/workflows/dependency-risk-identification.yml@main
        with:
            asset-name: "testorg-1/projects/testgroup/assets/testrepogithub"
            api-url: "https://api.main.devguard.org"
            sbom-file: "./results.sbom"
            web-ui: "https://main.devguard.org"
        secrets:
            devguard-token: "${{ secrets.DEVGUARD_TOKEN }}" 
